### ISSUE TITLE
Instructor Notes

### ISSUE THREAD

**Issue by bartdorsey** [b-tsui/Clack-App#1]
* Increase the granularity of the details around User support in your feature list, include things like user registration, error handling, and styling
* Perhaps consider implementing Live Chat functionality using setInterval polling via ajax calls, as opposed to using socket.io for your first version of the app.
* More details in the Live chat feature list about the interactions between multiple chat users.
* Combine items 3 4 and 5 into one feature. A channel can be conceptually the same as a DM, but just with a name, and also DM or channel can be chat between 2 or MORE users. 
* Consider dropping threads from your MVP implementation and added that to a list of bonus features you can add if you have time. 
* action cable is a technology for Ruby on Rails. The alternative for express based apps would be socket.io
* Think about how you will keep track of what users are in what channels.
* Consider moving channel creation out of Bonus features and into your MVP.
* Consider a bonus feature of controlling access to channels using role based authorization.

**Comment by bartdorsey** [comment]
## Data Schema

Looking pretty good, only a few things I noticed.

- The message should probably not be an `integer` probably better to make it a large `varchar` or a `text` 
- Instead of `creatorId` on channels, you might just have `userId`, it makes it more obvious what the foreign key is actually references without looking at the constraints and model definitions.

## Backend Routes

### Users
- POST /users/add - You don't need add here as POST already tells us what we are doing. Should just be POST /users
- PATCH /users/:id - This should be PUT /users/:id to be RESTful

### channels
- GET /channels/:channelId/members - should just be /channels/:channelId/users  don't have a different resource name between your routes and your models.
- POST /channels/add - Should just be POST /channels
- PATCH /channels/:channelId - Should be PUT /channels/:channelid

### messages
PATCH /messages/:id - Should be PUT /messages/:id 

Other than those things it looks good. 

You might want to consider trying out [socket.io](https://socket.io) for your real time messages. The team that is working on a Discord chat client clone is using it, and it looks really easy to use with express.  Check with Mark as he got a demo working really quickly, he could probably show you how it works. 

 ## Frontend Routes

So I would encourage you to try to implement some AJAX javascript only forms for some of the
things you have as routes. In particular the following would be nice to have as javascript powered pieces: 

/channels/add - This could be a popup javascript window that lets you type in a channel name, you'll notice the real slack does this instead of going to a regular page to add a channel.

/channels/:channelId/update - Same thing here, you could just pop something up to let the user change the channel details

One thing you also might consider, is eliminating /channels/:channelId, you'll notice the real slack just has a channel navigation sidebar, and when you click on the channel name, the message view just CHANGES to the right channel and loads that channels messages, instead of having to do an entire page load.  

This means your main route for chatting would just be /channels and everything that happens in there would be driven by javascript. I think you would find this would be a more pleasant and smoother User interface for a chat style app.

**Comment by bartdorsey** [comment]
Here's a link to the socket.io documentation for how to use it with Express: 

https://socket.io/docs/#Using-with-Express

**Comment by bartdorsey** [comment]
Although I believe the example they use there is outdated it seems to indicate you must use server.listen() instead of app.listen().... I believe Mark had it working in a different way.

**Comment by Seraph9** [comment]
I got socket.io working too last week but in a much different and easier way by the ways. It was pretty simple. I already did a demo for my group.
